const products = [
    {
        id: 1,
        name: "Xiaomi Google TV A L32M8-P2SEA",
        brand: "Xiaomi",
        size: "32 inch",
        resolution: "HD ",
        screenType: "LED",
        os: "Google TV",
        connectivity: "WiFi, HDMI, USB, Bluetooth",
        features: [
            "Hệ điều hành Google TV với kho ứng dụng phong phú",
            "Công nghệ hình ảnh Vivid Picture Engine",
            "Hỗ trợ Dolby Audio, DTS-HD",
            "Kết nối không dây đa dạng"
        ],
        price: "3.990.000₫",
        oldPrice: "4.590.000₫",
        discount: "-13%",
        rating: "4.8",
        sold: "13,7k",
        img: "../img/sp1.png",
        stock: true
    },
    {
        id: 2,
        name: "Samsung Smart TV UA43AU7002",
        brand: "Samsung",
        size: "43 inch",
        resolution: "Full HD ",
        screenType: "LED",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x2, USB x1",
        features: [
            "Công nghệ Crystal Display cho màu sắc sống động",
            "Bộ xử lý Crystal 4K",
            "Hỗ trợ HDR10+",
            "Tích hợp trình phát đa phương tiện"
        ],
        price: "8.400.000₫",
        oldPrice: "9.240.000₫",
        discount: "-9%",
        rating: "4.9",
        sold: "8.3k",
        img: "../img/sp2.png",
        stock: true
    },
    {
        id: 3,
        name: "TCL Google TV 55P635",
        brand: "TCL",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "QLED",
        os: "Google TV",
        connectivity: "WiFi, HDMI x3, USB x2, Bluetooth",
        features: [
            "Công nghệ QLED cho màu sắc rực rỡ",
            "Hỗ trợ Dolby Vision và HDR10+",
            "Âm thanh vòm Dolby Atmos",
            "Tích hợp Google Assistant và Chromecast"
        ],
        price: "8.490.000₫",
        oldPrice: "10.490.000₫",
        discount: "-19%",
        rating: "4.9",
        sold: "320",
        img: "../img/sp3.png",
        stock: true
    },
    {
        id: 4,
        name: "Xiaomi Google TV QLED A Pro L43MA-SSEA",
        brand: "Xiaomi",
        size: "43 inch",
        resolution: "4K Ultra HD ",
        screenType: "QLED",
        os: "Google TV",
        connectivity: "WiFi 6, HDMI 2.1 x3, USB 3.0 x2",
        features: [
            "Công nghệ QLED với dải màu rộng",
            "Hỗ trợ MEMC 120Hz",
            "Tích hợp Google TV với AI Recommendation",
            "Hệ thống âm thanh 30W Dolby Audio"
        ],
        price: "6.490.000₫",
        oldPrice: "7.990.000₫",
        discount: "-18%",
        rating: "4.8",
        sold: "2.7k",
        img: "../img/sp4.png",
        stock: true
    },
    {
        id: 5,
        name: "Samsung Smart TV Crystal UHD UA65CU8000",
        brand: "Samsung",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2, eARC",
        features: [
            "Công nghệ Crystal Processor 4K",
            "Hỗ trợ HDR10+, HLG",
            "Tích hợp trợ lý ảo Bixby",
            "Thiết kế viền mỏng tinh tế"
        ],
        price: "13.990.000₫",
        oldPrice: "15.490.000₫",
        discount: "-9%",
        rating: "4.9",
        sold: "3.8k",
        img: "../img/sp5.png",
        stock: true
    },
    {
        id: 6,
        name: "Samsung Smart TV OLED QA55S85C",
        brand: "Samsung",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "OLED",
        os: "Tizen OS",
        connectivity: "WiFi 6, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ OLED tự phát sáng",
            "Bộ xử lý Neural Quantum 4K",
            "Hỗ trợ HDR10+, Dolby Vision",
            "Âm thanh vòm Dolby Atmos 60W"
        ],
        price: "35.900.000₫",
        oldPrice: "40.500.000₫",
        discount: "-11%",
        rating: "4.9",
        sold: "13.7k",
        img: "../img/sp6.png",
        stock: true
    },
    {
        id: 7,
        name: "TCL Google TV 32S5400",
        brand: "TCL",
        size: "32 inch",
        resolution: "Full HD ",
        screenType: "LED",
        os: "Google TV",
        connectivity: "WiFi, HDMI x2, USB x1",
        features: [
            "Công nghệ HDR10 cho hình ảnh sáng tối rõ ràng",
            "Hệ điều hành Google TV dễ sử dụng",
            "Hỗ trợ Google Assistant điều khiển bằng giọng nói",
            "Tích hợp Chromecast built-in"
        ],
        price: "4.390.000₫",
        oldPrice: "4.790.000₫",
        discount: "-8%",
        rating: "4.9",
        sold: "21.4k",
        img: "../img/sp7.png",
        stock: true
    },
    {
        id: 8,
        name: "TCL Google TV 55P7B Pro",
        brand: "TCL",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "QLED",
        os: "Google TV",
        connectivity: "WiFi, HDMI 2.1 x3, USB x2",
        features: [
            "Công nghệ QLED với 120Hz Native",
            "Hỗ trợ Dolby Vision IQ và HDR10+",
            "Âm thanh vòm Dolby Atmos 50W",
            "Tích hợp trò chơi Game Master 2.0"
        ],
        price: "9.990.000₫",
        oldPrice: "11.990.000₫",
        discount: "-16%",
        rating: "4.9",
        sold: "5.6k",
        img: "../img/sp8.png",
        stock: true
    },
    {
        id: 9,
        name: "AQUA Android TV AQT43K38UGF",
        brand: "AQUA",
        size: "43 inch",
        resolution: "Full HD ",
        screenType: "LED",
        os: "Android TV",
        connectivity: "WiFi, HDMI x2, USB x1",
        features: [
            "Hệ điều hành Android TV 11",
            "Hỗ trợ Google Play Store",
            "Công nghệ hình ảnh A+ Grade Panel",
            "Tích hợp Chromecast và Google Assistant"
        ],
        price: "6.590.000₫",
        oldPrice: "7.490.000₫",
        discount: "-12%",
        rating: "4.8",
        sold: "1.6k",
        img: "../img/sp9.png",
        stock: true
    },
    {
        id: 10,
        name: "Samsung Smart TV Neo QLED QA65QN85B",
        brand: "Samsung",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "Neo QLED",
        os: "Tizen OS",
        connectivity: "WiFi 6, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ Neo Quantum Processor 4K",
            "Hỗ trợ HDR10+, HLG, Dolby Vision",
            "Thiết kế Infinity Screen viền cực mỏng",
            "Âm thanh Object Tracking Sound+ 60W"
        ],
        price: "29.900.000₫",
        oldPrice: "34.900.000₫",
        discount: "-14%",
        rating: "4.9",
        sold: "30k",
        img: "../img/sp10.png",
        stock: true
    },
    {
        id: 11,
        name: "Hisense Google TV 55A6500K",
        brand: "Hisense",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "UHD",
        os: "Google TV",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Công nghệ hình ảnh UHD Upscaling",
            "Hỗ trợ HDR10, HLG",
            "Hệ điều hành Google TV",
            "Âm thanh DTS Virtual:X"
        ],
        price: "7.990.000₫",
        oldPrice: "10.990.000₫",
        discount: "-27%",
        rating: "4.8",
        sold: "13.4k",
        img: "../img/sp11.png",
        stock: true
    },
    {
        id: 12,
        name: "Sony Google TV BRAVIA 3 K-55S30",
        brand: "Sony",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "LED",
        os: "Google TV",
        connectivity: "WiFi, HDMI 2.1 x4, USB x2",
        features: [
            "Bộ xử lý X1 4K HDR",
            "Công nghệ TRILUMINOS Pro",
            "Hỗ trợ Dolby Vision, IMAX Enhanced",
            "Âm thanh Acoustic Surface Audio"
        ],
        price: "17.890.000₫",
        oldPrice: "20.690.000₫",
        discount: "-14%",
        rating: "4.7",
        sold: "60k",
        img: "../img/sp12.png",
        stock: true
    },
    {
        id: 13,
        name: "Samsung Smart TV Crystal UHD UA85BU8000",
        brand: "Samsung",
        size: "85 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Màn hình cực lớn 85 inch",
            "Công nghệ Crystal UHD với PurColor",
            "Hỗ trợ HDR10+, HLG",
            "Tích hợp trợ lý ảo Bixby"
        ],
        price: "41.900.000₫",
        oldPrice: "43.900.000₫",
        discount: "-5%",
        rating: "4.9",
        sold: "42k",
        img: "../img/sp13.png",
        stock: true
    },
    {
        id: 14,
        name: "Samsung Smart TV Crystal UHD UA75CU8000",
        brand: "Samsung",
        size: "75 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Màn hình 75 inch Crystal UHD",
            "Bộ xử lý Crystal 4K",
            "Hỗ trợ HDR10+, HLG",
            "Thiết kế viền mỏng AirSlim"
        ],
        price: "25.400.000₫",
        oldPrice: "29.900.000₫",
        discount: "-15%",
        rating: "4.9",
        sold: "22.8k",
        img: "../img/sp14.png",
        stock: true
    },
    {
        id: 15,
        name: "LG Smart TV OLED 55B4PSA",
        brand: "LG",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "OLED",
        os: "webOS",
        connectivity: "WiFi, HDMI 2.1 x4, USB x3",
        features: [
            "Công nghệ OLED tự phát sáng",
            "Bộ xử lý α7 Gen6 AI Processor 4K",
            "Hỗ trợ Dolby Vision IQ, HDR10 Pro",
            "Âm thanh AI Sound Pro 40W"
        ],
        price: "25.900.000₫",
        oldPrice: "31.900.000₫",
        discount: "-19%",
        rating: "4.9",
        sold: "1.2k",
        img: "../img/sp15.png",
        stock: true
    },
    {
        id: 16,
        name: "Samsung Smart TV Crystal UHD UA85BU8000",
        brand: "Samsung",
        size: "85 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Màn hình siêu lớn 85 inch",
            "Công nghệ Crystal Display",
            "Hỗ trợ HDR10+, HLG",
            "Tích hợp trợ lý ảo Bixby, Alexa"
        ],
        price: "39.900.000₫",
        oldPrice: "45.800.000₫",
        discount: "-13%",
        rating: "4.9",
        sold: "65k",
        img: "../img/sp16.png",
        stock: true
    },
    {
        id: 17,
        name: "Samsung Smart TV OLED QA55S90D",
        brand: "Samsung",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "OLED",
        os: "Tizen OS",
        connectivity: "WiFi 6, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ OLED Quantum Dot",
            "Bộ xử lý Neural Quantum 4K",
            "Hỗ trợ HDR10+, Dolby Vision",
            "Âm thanh Object Tracking Sound Pro"
        ],
        price: "31.400.000₫",
        oldPrice: "39.800.000₫",
        discount: "-21%",
        rating: "4.9",
        sold: "64k",
        img: "../img/sp17.png",
        stock: true
    },
    {
        id: 18,
        name: "Samsung Smart TV Crystal UHD UA70BU8000",
        brand: "Samsung",
        size: "70 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Màn hình 70 inch Crystal UHD",
            "Công nghệ PurColor",
            "Hỗ trợ HDR10+, HLG",
            "Tích hợp trợ lý ảo Bixby"
        ],
        price: "26.560.000₫",
        oldPrice: "29.490.000₫",
        discount: "-10%",
        rating: "4.8",
        sold: "27.1k",
        img: "../img/sp18.png",
        stock: true
    },
    {
        id: 19,
        name: "Samsung Smart TV QLED QA65Q85B",
        brand: "Samsung",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "QLED",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ Quantum Dot 100% màu sắc",
            "Bộ xử lý Quantum 4K",
            "Hỗ trợ HDR10+, HLG",
            "Âm thanh Object Tracking Sound"
        ],
        price: "32.500.000₫",
        oldPrice: "39.900.000₫",
        discount: "-18%",
        rating: "4.5",
        sold: "20k",
        img: "../img/sp19.png",
        stock: true
    },
    {
        id: 20,
        name: "Samsung Smart TV QLED QA75Q65D",
        brand: "Samsung",
        size: "75 inch",
        resolution: "4K Ultra HD ",
        screenType: "QLED",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Màn hình QLED 75 inch",
            "Công nghệ Dual LED",
            "Hỗ trợ HDR10+, HLG",
            "Âm thanh OTS Lite 20W"
        ],
        price: "24.990.000₫",
        oldPrice: "32.090.000₫",
        discount: "-22%",
        rating: "4.9",
        sold: "2.6k",
        img: "../img/sp20.png",
        stock: true
    },
    {
        id: 21,
        name: "Samsung Smart TV Neo QLED QA65QN85D",
        brand: "Samsung",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "Neo QLED",
        os: "Tizen OS",
        connectivity: "WiFi 6, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ Neo Quantum Matrix",
            "Bộ xử lý Neo Quantum 4K",
            "Hỗ trợ HDR10+, HLG, Dolby Vision",
            "Âm thanh Dolby Atmos 60W"
        ],
        price: "25.400.000₫",
        oldPrice: "30.900.000₫",
        discount: "-17%",
        rating: "4.8",
        sold: "25.6k",
        img: "../img/sp21.png",
        stock: true
    },
    {
        id: 22,
        name: "Samsung Smart TV Crystal UHD UA98DU9000",
        brand: "Samsung",
        size: "98 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Màn hình siêu lớn 98 inch",
            "Công nghệ Crystal UHD",
            "Hỗ trợ HDR10+, HLG",
            "Tích hợp trợ lý ảo Bixby, Alexa"
        ],
        price: "54.900.000₫",
        oldPrice: "70.000.000₫",
        discount: "-22%",
        rating: "4.9",
        sold: "13k",
        img: "../img/sp22.png",
        stock: true
    },
    {
        id: 23,
        name: "Samsung Smart TV Neo QLED QA55QN85C",
        brand: "Samsung",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "Neo QLED",
        os: "Tizen OS",
        connectivity: "WiFi 6, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ Neo Quantum Matrix+",
            "Bộ xử lý Neo Quantum 4K",
            "Hỗ trợ HDR10+, HLG, Dolby Vision",
            "Âm thanh Object Tracking Sound+"
        ],
        price: "25.490.000₫",
        oldPrice: "30.900.000₫",
        discount: "-18%",
        rating: "4.9",
        sold: "14.9k",
        img: "../img/sp23.png",
        stock: true
    },
    {
        id: 24,
        name: "Samsung Smart TV Crystal UHD UA65BU8000",
        brand: "Samsung",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Công nghệ Crystal UHD",
            "Bộ xử lý Crystal 4K",
            "Hỗ trợ HDR10+, HLG",
            "Thiết kế viền mỏng AirSlim"
        ],
        price: "16.490.000₫",
        oldPrice: "19.490.000₫",
        discount: "-15%",
        rating: "4.9",
        sold: "38.8k",
        img: "../img/sp24.png",
        stock: true
    },
    {
        id: 25,
        name: "LG Smart TV NanoCell 65NANO78SQA",
        brand: "LG",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "NanoCell",
        os: "webOS",
        connectivity: "WiFi, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ Nano Color với hạt nano",
            "Bộ xử lý α7 Gen5 AI Processor 4K",
            "Hỗ trợ HDR10 Pro, HLG",
            "Âm thanh AI Sound Pro 40W"
        ],
        price: "15.890.000₫",
        oldPrice: "20.900.000₫",
        discount: "-24%",
        rating: "4.9",
        sold: "28k",
        img: "../img/sp25.png",
        stock: true
    },
    {
        id: 26,
        name: "Samsung Smart TV QLED QA55Q60B",
        brand: "Samsung",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "QLED",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Công nghệ Quantum Dot",
            "Bộ xử lý Quantum 4K",
            "Hỗ trợ HDR10+, HLG",
            "Âm thanh Dual Speaker 20W"
        ],
        price: "13.990.000₫",
        oldPrice: "16.800.000₫",
        discount: "-17%",
        rating: "4.9",
        sold: "28.7k",
        img: "../img/sp26.png",
        stock: true
    },
    {
        id: 27,
        name: "Samsung Smart TV QLED QA65Q85D",
        brand: "Samsung",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "QLED",
        os: "Tizen OS",
        connectivity: "WiFi 6, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ Quantum Dot 100% màu sắc",
            "Bộ xử lý Quantum 4K",
            "Hỗ trợ HDR10+, HLG, Dolby Vision",
            "Âm thanh Object Tracking Sound+"
        ],
        price: "30.990.000₫",
        oldPrice: "39.000.000₫",
        discount: "-21%",
        rating: "4.9",
        sold: "1.9k",
        img: "../img/sp27.png",
        stock: true
    },
    {
        id: 28,
        name: "Samsung Smart TV Crystal UHD UA65CU8000",
        brand: "Samsung",
        size: "65 inch",
        resolution: "4K Ultra HD ",
        screenType: "Crystal UHD",
        os: "Tizen OS",
        connectivity: "WiFi, HDMI x3, USB x2",
        features: [
            "Công nghệ Crystal UHD",
            "Bộ xử lý Crystal 4K",
            "Hỗ trợ HDR10+, HLG",
            "Thiết kế viền mỏng AirSlim"
        ],
        price: "13.400.000₫",
        oldPrice: "15.900.000₫",
        discount: "-16%",
        rating: "4.9",
        sold: "3.5k",
        img: "../img/sp28.png",
        stock: true
    },
    {
        id: 29,
        name: "LG Smart TV NanoCell 55NANO78SQA",
        brand: "LG",
        size: "55 inch",
        resolution: "4K Ultra HD ",
        screenType: "NanoCell",
        os: "webOS",
        connectivity: "WiFi, HDMI 2.1 x4, USB x2",
        features: [
            "Công nghệ Nano Color với hạt nano",
            "Bộ xử lý α7 Gen5 AI Processor 4K",
            "Hỗ trợ HDR10 Pro, HLG",
            "Âm thanh AI Sound Pro 40W"
        ],
        price: "13.890.000₫",
        oldPrice: "15.900.000₫",
        discount: "-13%",
        rating: "4.9",
        sold: "1.4k",
        img: "../img/sp29.png",
        stock: true
    },
    {
        id: 30,
        name: "TCL Google TV 43S5400",
        brand: "TCL",
        size: "43 inch",
        resolution: "Full HD ",
        screenType: "LED",
        os: "Google TV",
        connectivity: "WiFi, HDMI x2, USB x1",
        features: [
            "Hệ điều hành Google TV",
            "Công nghệ HDR10",
            "Hỗ trợ Google Assistant",
            "Tích hợp Chromecast built-in"
        ],
        price: "6.250.000₫",
        oldPrice: "6.790.000₫",
        discount: "-7%",
        rating: "4.9",
        sold: "6.5k",
        img: "../img/sp30.png",
        stock: true
    }
];
